---
version: 0.1
globalTimeout: 150
testSuiteTimeout: 150
testSuiteStep: 150

runson: linux

retryOnFailure: true
maxRetries: 1

# Pre-requisite commands - install dependencies
pre:
  - npm install newman newman-reporter-htmlextra
  - mkdir -p reports
  - echo "Starting Inwarranty Flow Tests..."
  - newman run "Inwarranty-flow Collection.postman_collection.json" -e "QA.postman_environment.json" -d "testData.csv" --reporters cli,htmlextra,json --reporter-htmlextra-export ./reports/newman-report.html --reporter-htmlextra-title "Inwarranty Flow Test Report" --reporter-json-export ./reports/newman-report.json --color on

# Post commands - verify report generation
post:
  - echo "Test execution completed!"
  - ls -lah reports/
  - cat reports/newman-report.json | head -50

# Job labels for identification
jobLabel: ['newman', 'inwarranty-flow', 'api-tests']
