version: 0.1
globalTimeout: 150
testSuiteTimeout: 150
testSuiteStep: 150
runson: linux
retryOnFailure: true
maxRetries: 1

# CRITICAL: Framework configuration
framework:
  name: "newman"
  defaultReports: false

# CRITICAL: Test discovery - defines what tests to run
testDiscovery:
  type: raw
  mode: static
  command: echo "newman-inwarranty-tests"

# CRITICAL: This is where your actual test execution happens
testRunnerCommand: newman run "Inwarranty-flow Collection.postman_collection.json" -e "QA.postman_environment.json" -d "testData.csv" --reporters cli,htmlextra,json,junit,./newman-hyperexecute-reporter.js --reporter-htmlextra-export reports/newman-report-$TASK_ID.html --reporter-htmlextra-title "Inwarranty Flow Test Report" --reporter-htmlextra-darkTheme --reporter-json-export reports/newman-report-$TASK_ID.json --reporter-junit-export reports/newman-report-$TASK_ID.xml --color on --bail false --verbose

# Install dependencies BEFORE tests run
pre:
  - npm install newman newman-reporter-htmlextra
  - mkdir -p reports
  - echo "Environment setup completed"
  - echo "Starting Newman test execution..."

# Post-execution summary
post:
  - echo "================================================"
  - echo "Test Execution Completed!"
  - echo "================================================"
  - ls -lah reports/ || echo "No reports found"
  - echo "Report files generated:"
  - find reports/ -type f 2>/dev/null || true

# CRITICAL: Report configuration for dashboard visibility
report: true
partialReports:
  location: reports
  type: json
  frameworkName: newman

# CRITICAL: Artifact upload configuration
mergeArtifacts: true
uploadArtefacts:
  - name: newman-html-reports
    path:
      - reports/**/*.html
  - name: newman-json-reports
    path:
      - reports/**/*.json
  - name: newman-junit-reports
    path:
      - reports/**/*.xml

# Job identification
jobLabel: ['newman', 'inwarranty-flow', 'api-tests']
