version: 0.1
globalTimeout: 150
testSuiteTimeout: 150
testSuiteStep: 150
runson: linux
retryOnFailure: true
maxRetries: 1

# Framework configuration
framework:
  name: "newman"
  defaultReports: false

# Test discovery - tells HyperExecute what tests to run
testDiscovery:
  type: raw
  mode: static
  command: echo "newman-tests"

# Test execution command - this is where your tests actually run
testRunnerCommand: |
  newman run "Inwarranty-flow Collection.postman_collection.json" \
    -e "QA.postman_environment.json" \
    -d "testData.csv" \
    --reporters cli,htmlextra,json,junit \
    --reporter-htmlextra-export ./reports/newman-report.html \
    --reporter-htmlextra-title "Inwarranty Flow Test Report" \
    --reporter-htmlextra-darkTheme \
    --reporter-json-export ./reports/newman-report.json \
    --reporter-junit-export ./reports/newman-report.xml \
    --color on \
    --bail false

# Install dependencies before test execution
pre:
  - npm install newman newman-reporter-htmlextra
  - mkdir -p reports
  - echo "Starting Inwarranty Flow Tests..."

# Post-execution commands
post:
  - echo "================================================"
  - echo "Test Execution Completed!"
  - echo "================================================"
  - ls -lah reports/ || true

# Artifact configuration - this uploads reports to HyperExecute
mergeArtifacts: true
uploadArtefacts:
  - name: newman-html-report
    path:
      - reports/**/*.html
  - name: newman-json-report
    path:
      - reports/**/*.json
  - name: newman-xml-report
    path:
      - reports/**/*.xml

# Report configuration for HyperExecute dashboard
report: true
partialReports:
  location: reports
  type: json
  frameworkName: newman

# Job labels
jobLabel: ['newman', 'inwarranty-flow', 'api-tests']
