version: 0.1
runson: linux

globalTimeout: 150
testSuiteTimeout: 150
testSuiteStep: 150

retryOnFailure: true
maxRetries: 1

pre:
  - echo "=== PRE STAGE ==="
  - npm install -g newman newman-reporter-htmlextra
  - mkdir -p reports
  - ls -la

# 🔥 RAW execution (THIS is the fix)
testDiscovery:
  type: raw
  mode: static
  command: echo "Running Newman via RAW runner"

testRunnerCommand: |
  echo "=== TEST STAGE STARTED ==="
  newman run "Inwarranty-flow Collection.postman_collection.json" \
    -e "QA.postman_environment.json" \
    -d "testData.csv" \
    -r cli,htmlextra \
    --reporter-htmlextra-export reports/newman-report.html \
    --reporter-htmlextra-title "Inwarranty Flow Test Report" \
    --reporter-htmlextra-darkTheme \
    --reporter-htmlextra-showOnlyFails \
    --color on \
    --suppress-exit-code

post:
  - echo "=== POST STAGE ==="
  - ls -lah reports
  - find reports -type f -name "*.html"

report: true
partialReports:
  - location: reports
    type: html
    frameworkName: newman

jobLabel:
  - newman
  - inwarranty-flow
  - api-tests
