---
version: 0.1

globalTimeout: 150
testSuiteTimeout: 150
testSuiteStep: 150

runson: linux

retryOnFailure: true
maxRetries: 1

# ---------------- PRE ----------------
pre:
  - echo "=== PRE STAGE STARTED ==="
  - node --version
  - npm --version
  - npm install newman newman-reporter-htmlextra
  - mkdir -p reports
  - echo "Dependencies installed"

# ---------------- TEST DISCOVERY ----------------
testDiscovery:
  type: raw
  mode: static
  command: echo "inwarranty-flow"

# ---------------- TEST EXECUTION ----------------
testRunnerCommand: >
  newman run "Inwarranty-flow Collection.postman_collection.json"
  -e "QA.postman_environment.json"
  -d "testData.csv"
  --reporters cli,htmlextra
  --reporter-htmlextra-export ./reports/newman-report.html
  --reporter-htmlextra-title "Inwarranty Flow Test Report"
  --reporter-htmlextra-darkTheme
  --reporter-htmlextra-showOnlyFails
  --color on
  --suppress-exit-code

# ---------------- POST ----------------
post:
  - echo "=== POST STAGE STARTED ==="
  - ls -lah reports/
  - echo "Report generated at reports/newman-report.html"

# ---------------- REPORTING ----------------
report: true
mergeArtifacts: true

uploadArtefacts:
  - name: newman-reports
    path: reports/**

jobLabel:
  - newman
  - inwarranty-flow
  - api-tests
