---
version: 0.1
globalTimeout: 150
testSuiteTimeout: 150
testSuiteStep: 150

runson: linux

retryOnFailure: true
maxRetries: 1

# Pre-requisite commands - install dependencies
pre:
  - npm install newman newman-reporter-htmlextra
  - mkdir -p reports
  - echo "Starting Inwarranty Flow Tests..."
  - |
    newman run "Inwarranty-flow Collection.postman_collection.json" \
      -e "QA.postman_environment.json" \
      -d "testData.csv" \
      --reporters cli,htmlextra \
      --reporter-htmlextra-export ./reports/newman-report.html \
      --reporter-htmlextra-title "Inwarranty Flow Test Report" \
      --reporter-htmlextra-darkTheme \
      --reporter-htmlextra-showOnlyFails \
      --color on \
      --suppress-exit-code || echo "Tests completed with failures"

# Post commands - display results
post:
  - echo "================================================"
  - echo "Test Execution Completed!"
  - echo "================================================"
  - ls -lah reports/
  - echo "Report generated at: reports/newman-report.html"

# CRITICAL: Enable report upload to HyperExecute dashboard
report: true

# Merge all artifacts into one
mergeArtifacts: true

# Upload artifacts - CORRECT SYNTAX
uploadArtefacts:
  - reports/**

# Job labels for identification
jobLabel: ['newman', 'inwarranty-flow', 'api-tests']
