---
version: 0.1
globalTimeout: 150
testSuiteTimeout: 150
testSuiteStep: 150

runson: linux

retryOnFailure: true
maxRetries: 1

env:
  REPORTS_DIR: reports

# Cache node_modules for faster execution
cacheKey: '{{ checksum "package.json" }}'
cacheDirectories:
  - node_modules

# Pre-requisite commands - Install dependencies
pre:
  - npm install newman
  - npm install newman-reporter-htmlextra
  - mkdir -p reports
  - echo "Starting Inwarranty Flow Tests..."

# Test discovery - Single test scenario
testDiscovery:
  type: raw
  mode: static
  command: echo "inwarranty-flow-test"

# Main test execution command
testRunnerCommand: newman run "collections/Inwarranty-flow Collection.postman_collection.json" -e "environments/QA.postman_environment.json" -d "data/testData.csv" --reporters cli,htmlextra,json --reporter-htmlextra-export ./reports/newman-report.html --reporter-htmlextra-title "Inwarranty Flow Test Report" --reporter-json-export ./reports/newman-report.json --color on --suppress-exit-code

# Post-test commands
post:
  - echo "Test execution completed!"
  - ls -lah reports/

# Job labels for identification
jobLabel: ['newman', 'inwarranty-flow', 'api-tests', 'qa-environment']
