version: 0.1
runson: linux

globalTimeout: 150
testSuiteTimeout: 150
testSuiteStep: 150

retryOnFailure: true
maxRetries: 1

# Pre-requisite commands - install dependencies
pre:
  - echo "=== PRE STAGE ==="
  - node --version
  - npm --version
  - npm install -g newman newman-reporter-htmlextra
  - mkdir -p reports
  - pwd
  - ls -la

# Test execution MUST be here
test:
  - name: Inwarranty_Flow_API_Tests
    commands:
      - echo "Starting Inwarranty Flow Tests..."
      - |
        newman run "collections/InwarrantyFlow.postman_collection.json" \
        -e "environments/QA.postman_environment.json" \
        -d "data/testData.csv" \
        -r cli,htmlextra \
        --reporter-htmlextra-export reports/newman-report.html \
        || echo "Newman completed with failures"

# Post commands - display results and reports
post:
  - echo "================================================"
  - echo "Test Execution Completed!"
  - echo "================================================"
  - ls -lah reports/
  - find reports -type f -name "*.html"

# Enable HyperExecute report pickup
report: true
partialReports:
  - location: reports
    type: html
    frameworkName: newman

# Job labels for identification
jobLabel:
  - newman
  - inwarranty-flow
  - api-tests
